export const DOMAIN_EVENTS = Object.freeze({
  APP_READY: "app.ready",
  APP_ERROR: "app.error",

  CLUB_UPDATED: "club.updated",
  SETTINGS_UPDATED: "settings.updated",
  TEAM_UPDATED: "team.updated",
  VENUE_UPDATED: "venue.updated",

  PITCH_REGISTRY_READY: "pitch.registry.ready",
  PITCH_UPDATED: "pitch.updated",
  PITCH_CLOSED: "pitch.closed",
  PITCH_REOPENED: "pitch.reopened",

  FIXTURES_IMPORTED: "fixtures.imported",
  FIXTURE_UPDATED: "fixture.updated",
  FIXTURE_POSTPONED: "fixture.postponed",
  FIXTURE_CANCELLED: "fixture.cancelled",

  SCHEDULE_REQUESTED: "schedule.requested",
  SCHEDULE_BUILT: "schedule.built",
  SCHEDULE_CHANGED: "schedule.changed",
  SCHEDULE_VALIDATED: "schedule.validated",
  SCHEDULE_VALIDATION_FAILED: "schedule.validation.failed",

  NAVIGATION_CHANGED: "navigation.changed",
  NAVIGATION_TARGET_SELECTED: "navigation.target.selected",

  PARKING_RECALCULATED: "parking.recalculated",
  WEATHER_UPDATED: "weather.updated",
  OFFICIALS_UPDATED: "officials.updated",
  HEALTH_UPDATED: "health.updated",
  RECOMMENDATIONS_UPDATED: "recommendations.updated",
  COMMUNICATIONS_UPDATED: "communications.updated",

  SERVICE_SYNC_STARTED: "service.sync.started",
  SERVICE_SYNC_COMPLETED: "service.sync.completed",
  SERVICE_SYNC_FAILED: "service.sync.failed",
});

export const PLATFORM_EVENT_GROUPS = Object.freeze({
  APP: [DOMAIN_EVENTS.APP_READY, DOMAIN_EVENTS.APP_ERROR],
  CLUB: [
    DOMAIN_EVENTS.CLUB_UPDATED,
    DOMAIN_EVENTS.SETTINGS_UPDATED,
    DOMAIN_EVENTS.TEAM_UPDATED,
    DOMAIN_EVENTS.VENUE_UPDATED,
  ],
  PITCH: [
    DOMAIN_EVENTS.PITCH_REGISTRY_READY,
    DOMAIN_EVENTS.PITCH_UPDATED,
    DOMAIN_EVENTS.PITCH_CLOSED,
    DOMAIN_EVENTS.PITCH_REOPENED,
  ],
  FIXTURE: [
    DOMAIN_EVENTS.FIXTURES_IMPORTED,
    DOMAIN_EVENTS.FIXTURE_UPDATED,
    DOMAIN_EVENTS.FIXTURE_POSTPONED,
    DOMAIN_EVENTS.FIXTURE_CANCELLED,
  ],
  SCHEDULE: [
    DOMAIN_EVENTS.SCHEDULE_REQUESTED,
    DOMAIN_EVENTS.SCHEDULE_BUILT,
    DOMAIN_EVENTS.SCHEDULE_CHANGED,
    DOMAIN_EVENTS.SCHEDULE_VALIDATED,
    DOMAIN_EVENTS.SCHEDULE_VALIDATION_FAILED,
  ],
  NAVIGATION: [
    DOMAIN_EVENTS.NAVIGATION_CHANGED,
    DOMAIN_EVENTS.NAVIGATION_TARGET_SELECTED,
  ],
  INTELLIGENCE: [
    DOMAIN_EVENTS.PARKING_RECALCULATED,
    DOMAIN_EVENTS.WEATHER_UPDATED,
    DOMAIN_EVENTS.OFFICIALS_UPDATED,
    DOMAIN_EVENTS.HEALTH_UPDATED,
    DOMAIN_EVENTS.RECOMMENDATIONS_UPDATED,
    DOMAIN_EVENTS.COMMUNICATIONS_UPDATED,
  ],
  SERVICE: [
    DOMAIN_EVENTS.SERVICE_SYNC_STARTED,
    DOMAIN_EVENTS.SERVICE_SYNC_COMPLETED,
    DOMAIN_EVENTS.SERVICE_SYNC_FAILED,
  ],
});
