export const GRANT_HOME_NATIONS = [
  { value: "england", label: "England" },
  { value: "scotland", label: "Scotland" },
  { value: "wales", label: "Wales" },
  { value: "northern-ireland", label: "Northern Ireland" },
];

export const GRANT_PROJECT_TYPES = [
  {
    value: "all",
    label: "All funding areas",
    description: "Explore every verified national and UK-wide opportunity in the selected home nation.",
    evidenceRequirementIds: ["organisation-identity", "sustained-demand", "monitoring-baseline"],
    qualityMeasureIds: ["history-depth", "fixture-identity", "allocation-coverage"],
  },
  {
    value: "grass-pitch",
    label: "Grass pitches, drainage and maintenance",
    description: "Drainage, renovation, maintenance machinery, pitch quality and new natural grass provision.",
    evidenceRequirementIds: ["sustained-demand", "facility-use", "reliability-resilience", "monitoring-baseline"],
    qualityMeasureIds: ["history-depth", "fixture-identity", "format-coverage", "allocation-coverage", "weather-coverage"],
  },
  {
    value: "artificial-pitch",
    label: "3G and artificial pitches",
    description: "New or improved artificial playing surfaces, small-sided areas and supporting infrastructure.",
    evidenceRequirementIds: ["sustained-demand", "facility-use", "reliability-resilience", "participation-opportunity", "monitoring-baseline"],
    qualityMeasureIds: ["history-depth", "fixture-identity", "format-coverage", "allocation-coverage"],
  },
  {
    value: "clubhouse",
    label: "Clubhouse, changing and community facilities",
    description: "Changing rooms, pavilions, community hubs, toilets, catering and accessibility improvements.",
    evidenceRequirementIds: ["sustained-demand", "participation-opportunity", "inclusion-reach", "site-access", "monitoring-baseline"],
    qualityMeasureIds: ["history-depth", "fixture-identity", "allocation-coverage", "parking-coverage"],
  },
  {
    value: "floodlights",
    label: "Floodlights and evening capacity",
    description: "Permanent or portable lighting, winter capacity and safer evening use.",
    evidenceRequirementIds: ["sustained-demand", "facility-use", "participation-opportunity", "monitoring-baseline"],
    qualityMeasureIds: ["history-depth", "fixture-identity", "allocation-coverage"],
  },
  {
    value: "equipment",
    label: "Equipment, goals and storage",
    description: "Goalposts, training and match equipment, grounds equipment, storage and site security.",
    evidenceRequirementIds: ["sustained-demand", "facility-use", "workforce", "monitoring-baseline"],
    qualityMeasureIds: ["history-depth", "fixture-identity", "format-coverage"],
  },
  {
    value: "participation",
    label: "Participation and new teams",
    description: "New teams, targeted activity, facility hire, affiliation, coaching and reducing barriers to play.",
    evidenceRequirementIds: ["participation-opportunity", "inclusion-reach", "sustained-demand", "monitoring-baseline"],
    qualityMeasureIds: ["history-depth", "fixture-identity", "format-coverage"],
  },
  {
    value: "women-girls",
    label: "Women and girls",
    description: "New teams, inclusive environments, equipment, coaching, facility access and retention.",
    evidenceRequirementIds: ["participation-opportunity", "inclusion-reach", "facility-use", "monitoring-baseline"],
    qualityMeasureIds: ["history-depth", "fixture-identity", "format-coverage", "allocation-coverage"],
  },
  {
    value: "disability-inclusion",
    label: "Disability and inclusion",
    description: "Accessible facilities, targeted participation, equipment and projects addressing inequality.",
    evidenceRequirementIds: ["inclusion-reach", "participation-opportunity", "site-access", "monitoring-baseline"],
    qualityMeasureIds: ["history-depth", "fixture-identity", "allocation-coverage", "parking-coverage"],
  },
  {
    value: "workforce",
    label: "Coaches, officials and volunteers",
    description: "Recruitment, qualifications, workforce capacity, governance and volunteer development.",
    evidenceRequirementIds: ["workforce", "participation-opportunity", "monitoring-baseline"],
    qualityMeasureIds: ["history-depth", "fixture-identity", "officials-coverage"],
  },
  {
    value: "parking-access",
    label: "Parking, travel and site access",
    description: "Parking, safer arrivals, hard standing, fencing, paths and access infrastructure.",
    evidenceRequirementIds: ["site-access", "sustained-demand", "facility-use", "monitoring-baseline"],
    qualityMeasureIds: ["history-depth", "fixture-identity", "allocation-coverage", "parking-coverage"],
  },
  {
    value: "sustainability",
    label: "Energy and environmental sustainability",
    description: "Solar, LED lighting, heating, water saving, biodiversity and climate resilience.",
    evidenceRequirementIds: ["facility-use", "reliability-resilience", "monitoring-baseline"],
    qualityMeasureIds: ["history-depth", "fixture-identity", "allocation-coverage", "weather-coverage"],
  },
  {
    value: "community",
    label: "Community programmes and wellbeing",
    description: "Community-led activity, wellbeing, cost-of-living support and projects tackling inactivity.",
    evidenceRequirementIds: ["participation-opportunity", "inclusion-reach", "sustained-demand", "monitoring-baseline"],
    qualityMeasureIds: ["history-depth", "fixture-identity", "format-coverage"],
  },
  {
    value: "asset-transfer",
    label: "Land, buildings and asset transfer",
    description: "Community asset transfer, long leases, land purchase and sustainable facility ownership.",
    evidenceRequirementIds: ["organisation-identity", "sustained-demand", "facility-use", "monitoring-baseline"],
    qualityMeasureIds: ["history-depth", "fixture-identity", "allocation-coverage"],
  },
];

const VERIFIED_ON = "2026-07-11";

function programme(programme) {
  return {
    sourceType: "official",
    lastVerified: VERIFIED_ON,
    coverageLevel: "national",
    applicantTypes: ["not-for-profit club", "charity", "community organisation"],
    manualRequirements: ["Current governing document", "Organisation bank account", "Project budget", "Supplier quotations where required"],
    requiredDocuments: [],
    verificationBasis: "Official programme guidance",
    ...programme,
  };
}

export const VERIFIED_GRANT_PROGRAMMES = [
  programme({
    id: "ff-grass-pitch-drainage",
    funder: "Football Foundation",
    name: "Grass Pitch Drainage",
    nations: ["england"],
    status: "rolling",
    amountLabel: "Up to £25,000 through the standard route; larger projects require discussion",
    projectTypes: ["grass-pitch"],
    summary: "Capital drainage works recommended through a PitchPower assessment where improved maintenance alone is not enough.",
    matchFunding: "Normally up to 75% through the standard route",
    eligibilityNotes: ["Grassroots football must be integral to the site", "PitchPower assessment required", "Landlord consent and tenure requirements apply"],
    evidenceRequirementIds: ["sustained-demand", "facility-use", "reliability-resilience", "monitoring-baseline"],
    manualRequirements: ["PitchPower assessment", "Photographs", "Design or feasibility evidence", "Two like-for-like quotations", "Partnership funding evidence", "Landlord or regulatory consent where applicable"],
    officialUrl: "https://footballfoundation.org.uk/grant/grass-pitch-drainage",
  }),
  programme({
    id: "ff-grass-maintenance-equipment",
    funder: "Football Foundation",
    name: "Grass Pitch Maintenance Machinery and Equipment",
    nations: ["england"],
    status: "rolling",
    amountLabel: "Project-specific grant contribution",
    projectTypes: ["grass-pitch", "equipment"],
    summary: "Machinery and equipment specifically recommended through a PitchPower assessment to improve grass pitch quality.",
    matchFunding: "Partnership funding evidence required",
    eligibilityNotes: ["PitchPower recommendation required", "Two trained operators required", "Secure storage and insurance expected"],
    evidenceRequirementIds: ["facility-use", "reliability-resilience", "workforce", "monitoring-baseline"],
    manualRequirements: ["PitchPower assessment", "Two quotations", "Partnership funding evidence", "Secure storage photographs", "GMA Level 1 certificates"],
    officialUrl: "https://footballfoundation.org.uk/grant/grass-pitch-maintenance-machinery-and-equipment",
  }),
  programme({
    id: "ff-grass-pitch-maintenance-fund",
    funder: "Football Foundation",
    name: "Grass Pitch Maintenance Fund",
    nations: ["england"],
    status: "rolling",
    amountLabel: "Six-year tapered maintenance grant",
    projectTypes: ["grass-pitch"],
    summary: "Revenue support for enhanced grass-pitch maintenance over six years, with the aim of reaching or sustaining the GMA Good standard.",
    matchFunding: "Tapered contribution; check the current PitchPower recommendation and award profile",
    eligibilityNotes: ["PitchPower assessment required", "Eligible security of tenure or an accepted maintenance agreement is required", "Commercial and sole-trader applicants are not eligible"],
    evidenceRequirementIds: ["sustained-demand", "facility-use", "reliability-resilience", "workforce", "monitoring-baseline"],
    manualRequirements: ["PitchPower assessment", "Tenure or maintenance agreement", "Six-year maintenance plan", "Contractor or materials quotations", "Grounds workforce plan"],
    officialUrl: "https://footballfoundation.org.uk/grant/grass-pitch-maintenance-fund",
  }),
  programme({
    id: "ff-3g-maintenance-equipment",
    funder: "Football Foundation",
    name: "3G Pitch Maintenance Machinery and Equipment",
    nations: ["england"],
    status: "rolling",
    amountLabel: "Up to £25,000",
    projectTypes: ["artificial-pitch", "equipment"],
    summary: "Maintenance machinery and equipment for eligible 3G pitches, supported by pitch-test or register evidence and supplier recommendations.",
    matchFunding: "Partnership funding evidence required",
    eligibilityNotes: ["Pitch test certificate or FA 3G Pitch Register route required", "Equipment must be recommended by the manufacturer, installer or specialist", "Secure storage is expected"],
    evidenceRequirementIds: ["facility-use", "reliability-resilience", "workforce", "monitoring-baseline"],
    manualRequirements: ["3G pitch test or register evidence", "Two like-for-like quotations", "Partnership funding evidence", "Storage photographs", "Equipment recommendation"],
    officialUrl: "https://footballfoundation.org.uk/grant/3g-maintenance",
  }),
  programme({
    id: "ff-clubhouse-changing",
    funder: "Football Foundation",
    name: "Changing Pavilions and Clubhouses",
    nations: ["england"],
    status: "rolling",
    amountLabel: "Up to £25,000 through the published small-grant route; larger projects require discussion",
    projectTypes: ["clubhouse", "disability-inclusion", "sustainability"],
    summary: "Minor and major building works to improve changing rooms, toilets, clubhouses, accessibility, safety, operating costs and income generation.",
    matchFunding: "Published small-grant route normally funds no more than 75%",
    eligibilityNotes: ["Contact the County FA or Foundation Delivery Manager before applying", "Routine maintenance alone is not eligible", "Planning, building regulations and tenure may apply"],
    evidenceRequirementIds: ["sustained-demand", "participation-opportunity", "inclusion-reach", "facility-use", "monitoring-baseline"],
    manualRequirements: ["Condition survey or equivalent need evidence", "Photographs", "Specifications and drawings", "Planning or building-control evidence", "Two quotations", "Tenure and landlord consent", "Project budget"],
    officialUrl: "https://footballfoundation.org.uk/grant/changing-pavilions-and-clubhouses",
  }),
  programme({
    id: "ff-storage-containers",
    funder: "Football Foundation",
    name: "Storage Containers",
    nations: ["england"],
    status: "rolling",
    amountLabel: "Up to £25,000",
    projectTypes: ["equipment", "clubhouse"],
    summary: "Secure on-site storage containers for club and grounds equipment, including new or eligible refurbished units.",
    matchFunding: "Partnership funding evidence required",
    eligibilityNotes: ["Container must be stored at the applicant site", "Insurance and planning evidence may be required", "Five-year clawback responsibilities apply"],
    evidenceRequirementIds: ["facility-use", "workforce", "monitoring-baseline"],
    manualRequirements: ["Two like-for-like quotations", "Partnership funding evidence", "Site drawing or aerial photograph", "Planning approval or exemption", "Landlord consent", "Insurance confirmation"],
    officialUrl: "https://footballfoundation.org.uk/grant/storage-containers",
  }),
  programme({
    id: "ff-portable-floodlights",
    funder: "Football Foundation",
    name: "Portable Floodlights",
    nations: ["england"],
    status: "rolling",
    amountLabel: "Up to £25,000",
    projectTypes: ["floodlights", "equipment", "participation"],
    summary: "New or eligible used portable floodlights for training areas on natural or artificial turf, with secure storage and safe-operation requirements.",
    matchFunding: "Check the current contribution requirements",
    eligibilityNotes: ["Grass match pitches are not eligible for portable-floodlight matchplay", "Additional use and pitch rotation must be explained", "Trained adult operators and secure storage are required"],
    evidenceRequirementIds: ["sustained-demand", "facility-use", "participation-opportunity", "workforce", "monitoring-baseline"],
    manualRequirements: ["Lighting need and usage plan", "Quotations", "Storage photographs", "Insurance evidence", "Operator arrangements", "Partnership funding evidence where requested"],
    officialUrl: "https://footballfoundation.org.uk/grant/portable-floodlights",
  }),
  programme({
    id: "ff-fencing",
    funder: "Football Foundation",
    name: "Fencing",
    nations: ["england"],
    status: "rolling",
    amountLabel: "Up to £25,000",
    projectTypes: ["parking-access", "equipment", "clubhouse"],
    summary: "New or replacement site fencing that improves security, safety or operational control at grassroots football facilities.",
    matchFunding: "Check the current contribution requirements",
    eligibilityNotes: ["Need and site benefit must be demonstrated", "One site per application is normally expected", "Planning and landlord consent may apply"],
    evidenceRequirementIds: ["site-access", "facility-use", "sustained-demand", "monitoring-baseline"],
    manualRequirements: ["Site plan", "Photographs", "Two quotations", "Planning or landlord consent", "Project budget", "Security or safety case"],
    officialUrl: "https://footballfoundation.org.uk/grant/fencing",
  }),
  programme({
    id: "ff-catering-unit",
    funder: "Football Foundation",
    name: "Catering Units",
    nations: ["england"],
    status: "rolling",
    amountLabel: "Up to £50,000",
    projectTypes: ["clubhouse", "community", "sustainability"],
    summary: "New or upgraded catering units designed to improve the matchday offer and create sustainable site income.",
    matchFunding: "Check the current programme guidance and approved specification",
    eligibilityNotes: ["The unit must meet the Foundation specification", "Site sustainability and income generation must be demonstrated", "Planning and statutory approvals may apply"],
    evidenceRequirementIds: ["sustained-demand", "facility-use", "participation-opportunity", "monitoring-baseline"],
    manualRequirements: ["Business and income plan", "Preferred-supplier quotation", "Site plan", "Planning and landlord consent", "Utilities and operating plan", "Project budget"],
    officialUrl: "https://footballfoundation.org.uk/grant/Catering-Unit",
  }),
  programme({
    id: "ff-goalposts",
    funder: "Football Foundation",
    name: "Goalposts",
    nations: ["england"],
    status: "rolling",
    amountLabel: "£400 to £25,000; normally no more than 75% of project cost",
    projectTypes: ["equipment"],
    summary: "New or replacement goalposts purchased in pairs from approved suppliers, including currently open 3v3 goalpost applications.",
    matchFunding: "Applicant contribution normally required",
    eligibilityNotes: ["Approved suppliers only", "Formal supplier quotation required", "Retrospective purchases are not eligible"],
    evidenceRequirementIds: ["sustained-demand", "facility-use", "participation-opportunity"],
    manualRequirements: ["Formal supplier quotation", "Organisation documents", "Partnership funding evidence"],
    officialUrl: "https://footballfoundation.org.uk/grant/goalposts",
  }),
  programme({
    id: "ff-small-sided-surfaces",
    funder: "Football Foundation",
    name: "Small-Sided Playing Surface Improvements",
    nations: ["england"],
    status: "rolling",
    amountLabel: "Up to £25,000",
    projectTypes: ["artificial-pitch", "participation"],
    summary: "Improvements to small-sided artificial pitches, including surfaces up to the Foundation's stated size limit.",
    matchFunding: "Check current guidance for contribution requirements",
    eligibilityNotes: ["Grassroots football must be integral", "One application per season is normally expected", "One site per application"],
    evidenceRequirementIds: ["sustained-demand", "facility-use", "reliability-resilience", "participation-opportunity"],
    manualRequirements: ["Site plans", "Condition evidence", "Supplier quotations", "Tenure evidence", "Project budget"],
    officialUrl: "https://footballfoundation.org.uk/grant/playing-surface-improvement",
  }),
  programme({
    id: "ff-new-grass-pitch",
    funder: "Football Foundation",
    name: "New Grass Pitches",
    nations: ["england"],
    status: "rolling",
    amountLabel: "Up to £25,000 through the published small-grant route",
    projectTypes: ["grass-pitch"],
    summary: "Support toward creating new natural grass playing areas to sustain or increase participation.",
    matchFunding: "Check current project contribution requirements",
    eligibilityNotes: ["Grassroots football must be integral", "One site per application", "Planning and tenure may be required"],
    evidenceRequirementIds: ["sustained-demand", "facility-use", "participation-opportunity", "monitoring-baseline"],
    manualRequirements: ["Site plan", "Planning or landlord approvals", "Quotations", "Tenure evidence", "Project budget"],
    officialUrl: "https://footballfoundation.org.uk/grant/new-grass-pitch",
  }),
  programme({
    id: "ff-3g-pitch",
    funder: "Football Foundation",
    name: "3G Pitch Development",
    nations: ["england"],
    status: "development",
    amountLabel: "Project-specific capital investment",
    projectTypes: ["artificial-pitch", "floodlights", "clubhouse"],
    summary: "Development route for FIFA Quality Standard 3G provision, normally aligned to local facility planning and Foundation support.",
    matchFunding: "Project-specific partnership funding",
    eligibilityNotes: ["Early discussion with the County FA or Foundation is required", "Strategic need and long-term sustainability must be demonstrated"],
    evidenceRequirementIds: ["sustained-demand", "facility-use", "reliability-resilience", "participation-opportunity", "inclusion-reach", "monitoring-baseline"],
    manualRequirements: ["Feasibility study", "Business plan", "Planning", "Tenure", "Usage plan", "Community consultation", "Lifecycle replacement plan"],
    officialUrl: "https://footballfoundation.org.uk/grant/3g-pitch",
  }),
  programme({
    id: "ff-home-advantage",
    funder: "Football Foundation",
    name: "Home Advantage Programme",
    nations: ["england"],
    status: "closed",
    amountLabel: "100% grants up to £250,000",
    projectTypes: ["asset-transfer", "grass-pitch", "equipment", "clubhouse", "floodlights"],
    summary: "Supports long-term community asset transfer of local-authority grass pitch sites, with capital and revenue items included.",
    matchFunding: "100% grant route, subject to programme rules",
    eligibilityNotes: ["Year-two expression-of-interest window is closed", "Local authority and County FA support required", "Minimum 25-year lease required"],
    evidenceRequirementIds: ["organisation-identity", "sustained-demand", "facility-use", "workforce", "monitoring-baseline"],
    manualRequirements: ["Local-authority partnership", "County FA support", "PitchPower inspection", "Heads of terms or lease", "Business and sustainability plan"],
    officialUrl: "https://footballfoundation.org.uk/grant/home-advantage-programme",
  }),
  programme({
    id: "ff-lionesses-here-to-play",
    funder: "Football Foundation",
    name: "Lionesses HERe to Play Fund – Teams",
    nations: ["england"],
    status: "open",
    deadline: "2026-09-30",
    amountLabel: "£500 to £7,500 across up to five opportunities",
    projectTypes: ["women-girls", "participation", "equipment", "workforce"],
    summary: "Set-up support for new women and girls' teams or eligible England Football programmes, including kit, equipment and programme costs.",
    matchFunding: "No match-funding requirement stated on the official team guidance",
    eligibilityNotes: ["New team or eligible England Football programme", "Organisations can combine up to five opportunities", "Fund closes 30 September 2026", "Club applicants must meet the relevant inclusion-workshop condition"],
    requiredDocuments: ["New-team or programme plan", "Costed budget", "Safeguarding arrangements"],
    evidenceRequirementIds: ["participation-opportunity", "inclusion-reach", "workforce"],
    manualRequirements: ["New-team plan", "Budget", "Affiliation or programme details", "Safeguarding arrangements", "Verified organisation, contacts and site"],
    officialUrl: "https://footballfoundation.org.uk/grant/lionesses-here-to-play/here-for-teams",
  }),
  programme({
    id: "ff-lionesses-here-to-play-facilities",
    funder: "Football Foundation",
    name: "Lionesses HERe to Play Fund – Facilities",
    nations: ["england"],
    status: "open",
    deadline: "2026-09-30",
    amountLabel: "Up to £25,000; no more than 75% of total project cost",
    projectTypes: ["clubhouse", "equipment", "women-girls", "disability-inclusion", "parking-access"],
    summary: "Facility improvements intended to make grassroots sites more welcoming, safe and inclusive for women and girls.",
    matchFunding: "Applicant must provide at least 25% partnership funding",
    eligibilityNotes: ["Minimum five years' security of tenure", "No retrospective costs or commitments", "Fund closes 30 September 2026", "Planning and building-regulation requirements must be checked"],
    requiredDocuments: ["Tenure evidence", "Two quotations for each requested item", "Partnership-funding evidence", "Planning or building-regulation evidence where relevant"],
    evidenceRequirementIds: ["sustained-demand", "participation-opportunity", "inclusion-reach", "site-access", "monitoring-baseline"],
    manualRequirements: ["Tenure evidence", "Two quotes for each requested item", "Planning or building-regulation evidence where relevant", "Evidence of at least 25% partnership funding", "Project plan and photographs", "Safeguarding and inclusion case"],
    officialUrl: "https://footballfoundation.org.uk/grant/lionesses-here-to-play/here-for-facilities",
  }),
  programme({
    id: "sport-england-movement-fund",
    funder: "Sport England",
    name: "Movement Fund",
    nations: ["england"],
    status: "rolling",
    amountLabel: "£300 to £15,000",
    projectDuration: "Up to 12 months",
    decisionTime: "Usually 6 to 8 weeks; apply at least 12 weeks before spending",
    projectTypes: ["participation", "women-girls", "disability-inclusion", "community", "equipment", "sustainability", "clubhouse"],
    summary: "Grants or crowdfunding pledges for projects that get more people active, reduce inequalities, improve spaces or strengthen delivery capacity.",
    matchFunding: "Grant or crowdfunding pledge; Sport England decides the route",
    eligibilityNotes: ["Priority is given to tackling inactivity and inequality", "Projects can run for up to 12 months", "Apply at least 12 weeks before spending"],
    evidenceRequirementIds: ["participation-opportunity", "inclusion-reach", "sustained-demand", "monitoring-baseline"],
    manualRequirements: ["Community need", "Target beneficiaries", "Delivery plan", "Budget", "Measurable outcomes", "Safeguarding and governance evidence"],
    requiredDocuments: ["Constitution or governing document", "Organisation bank details", "Costed project plan", "Safeguarding evidence where relevant"],
    officialUrl: "https://www.sportengland.org/funding-and-campaigns/our-funding/movement-fund",
  }),
  programme({
    id: "tnl-awards-all-england",
    funder: "The National Lottery Community Fund",
    name: "Awards for All England",
    nations: ["england"],
    status: "open",
    amountLabel: "£300 to £20,000",
    projectDuration: "Up to two years",
    decisionTime: "Around 16 weeks",
    projectTypes: ["participation", "community", "women-girls", "disability-inclusion", "equipment", "clubhouse", "workforce"],
    summary: "Community-led projects that bring people together, improve places and help people reach their potential.",
    matchFunding: "No standard match-funding requirement stated on the programme overview",
    eligibilityNotes: ["Projects can last up to two years", "Community benefit must be clear", "Decision target is around 16 weeks"],
    evidenceRequirementIds: ["participation-opportunity", "inclusion-reach", "sustained-demand", "monitoring-baseline"],
    manualRequirements: ["Community need", "Project plan", "Budget", "Organisation details", "Safeguarding where relevant", "Outcome plan"],
    requiredDocuments: ["Organisation details", "Project budget", "Bank details", "Safeguarding information where relevant"],
    officialUrl: "https://www.tnlcommunityfund.org.uk/funding/funding-programmes/national-lottery-awards-for-all-england",
  }),
  programme({
    id: "tnl-awards-all-england-environment",
    funder: "The National Lottery Community Fund",
    name: "Awards for All England – Environment",
    nations: ["england"],
    status: "open",
    amountLabel: "£300 to £20,000",
    projectTypes: ["sustainability", "community", "clubhouse"],
    summary: "Community-led climate and nature projects that improve the environment and connect people with local green space.",
    matchFunding: "No standard match-funding requirement stated on the programme overview",
    eligibilityNotes: ["The environmental outcome must be central", "Decision target is around 16 weeks"],
    evidenceRequirementIds: ["facility-use", "reliability-resilience", "participation-opportunity", "monitoring-baseline"],
    manualRequirements: ["Environmental need", "Project plan", "Community involvement", "Budget", "Measurable environmental outcomes"],
    officialUrl: "https://www.tnlcommunityfund.org.uk/funding/funding-programmes/national-lottery-awards-for-all-england-environment",
  }),
  programme({
    id: "fcc-community-action-fund",
    funder: "FCC Communities Foundation",
    name: "FCC Community Action Fund",
    nations: ["england"],
    status: "open",
    deadline: "2026-08-19",
    amountLabel: "£10,000 to £100,000",
    projectTypes: ["clubhouse", "parking-access", "community", "sustainability", "equipment"],
    summary: "Capital improvements to community amenities, including sports and recreation grounds, pavilions and clubhouses with public access.",
    matchFunding: "Third-party contribution and Landfill Communities Fund rules apply",
    eligibilityNotes: ["Project site must be in an eligible FCC funding area", "Public access and eligible ownership or lease arrangements are required", "Current round closes 19 August 2026"],
    evidenceRequirementIds: ["organisation-identity", "sustained-demand", "facility-use", "site-access", "monitoring-baseline"],
    manualRequirements: ["Location eligibility check", "Land ownership or lease", "Planning permissions", "Quotations", "Third-party contribution", "Public access evidence"],
    officialUrl: "https://fcccommunitiesfoundation.org.uk/funds/fcc-community-action-fund",
  }),
  programme({
    id: "veolia-environmental-trust",
    funder: "Veolia Environmental Trust",
    name: "Community Grants",
    nations: ["england"],
    status: "rolling",
    amountLabel: "Project-specific awards through funding rounds",
    projectTypes: ["clubhouse", "community", "sustainability", "parking-access", "equipment"],
    summary: "Landfill Communities Fund support for community facilities and environmental projects in eligible areas of England, including sports clubs.",
    matchFunding: "Landfill Communities Fund contribution rules apply",
    eligibilityNotes: ["The site must pass the official location checker", "Community access and eligible organisation rules apply", "Application windows and criteria must be checked before submission"],
    evidenceRequirementIds: ["organisation-identity", "sustained-demand", "facility-use", "participation-opportunity"],
    manualRequirements: ["Location eligibility check", "Tenure", "Quotations", "Planning", "Community access evidence", "Contributing third-party arrangements where required"],
    officialUrl: "https://www.veoliatrust.org/",
  }),
  programme({
    id: "aviva-communities-fund",
    funder: "Aviva Foundation",
    name: "Communities Fund",
    nations: ["england", "scotland", "wales", "northern-ireland"],
    status: "rolling",
    coverageLevel: "uk-wide",
    amountLabel: "Crowdfunding match support; award terms vary",
    projectTypes: ["sustainability", "community"],
    summary: "Crowdfunding support for eligible charities and non-profits focused on climate action or financial wellbeing.",
    matchFunding: "Crowdfunding and Aviva match-funding model",
    eligibilityNotes: ["Project must address climate action or financial wellbeing", "Legal-form restrictions apply", "Organisation income and operating-history limits apply"],
    evidenceRequirementIds: ["organisation-identity", "participation-opportunity", "inclusion-reach", "monitoring-baseline"],
    manualRequirements: ["Eligible legal form", "Published financial information", "Project story", "Crowdfunding plan", "Safeguarding policy where relevant"],
    officialUrl: "https://www.avivacommunityfund.co.uk/eligibility-criteria",
  }),
  programme({
    id: "cff-fit-for-future-eoi",
    funder: "Cymru Football Foundation",
    name: "Fit for Future Facilities Programme – Expression of Interest",
    nations: ["wales"],
    status: "open",
    amountLabel: "Large and small capital grants; project-specific award",
    projectTypes: ["grass-pitch", "artificial-pitch", "clubhouse", "floodlights", "parking-access", "disability-inclusion"],
    summary: "A live expression-of-interest route for UK Government-funded capital projects, from grass-pitch improvements to changing-room developments.",
    matchFunding: "Project-specific; confirm through the current EOI guidance",
    eligibilityNotes: ["Capital football-facility project in Wales", "Submit an expression of interest before relying on a full application route", "Current guidance and local facility priorities must be checked"],
    evidenceRequirementIds: ["sustained-demand", "facility-use", "reliability-resilience", "participation-opportunity", "inclusion-reach", "site-access", "monitoring-baseline"],
    manualRequirements: ["Expression of interest", "Project concept", "Site and tenure details", "Estimated budget", "Demand evidence", "Community and inclusion case", "Delivery readiness"],
    officialUrl: "https://faw.cymru/cff/fit-for-future-facilities-programme-eoi/",
  }),
  programme({
    id: "cff-equipment-fund",
    funder: "Cymru Football Foundation",
    name: "Equipment Fund",
    nations: ["wales"],
    status: "closed",
    amountLabel: "Up to £30,000",
    projectTypes: ["equipment", "grass-pitch", "parking-access"],
    summary: "Equipment support including grounds maintenance equipment, storage containers, security fencing and related club infrastructure.",
    matchFunding: "Check the current funding guidance",
    eligibilityNotes: ["Grassroots football organisation in Wales", "Current application guidance must be checked"],
    evidenceRequirementIds: ["facility-use", "sustained-demand", "workforce", "monitoring-baseline"],
    manualRequirements: ["Equipment need", "Quotations", "Storage and security arrangements", "Project budget", "Organisation documents"],
    officialUrl: "https://faw.cymru/cff/equipment-fund/",
  }),
  programme({
    id: "cff-facilities-programme",
    funder: "Cymru Football Foundation",
    name: "Facilities Programme",
    nations: ["wales"],
    status: "closed",
    amountLabel: "Up to £500,000",
    projectTypes: ["artificial-pitch", "grass-pitch", "clubhouse", "floodlights", "parking-access"],
    summary: "Capital support for artificial pitches, grass pitches, changing rooms, clubhouses and community hubs.",
    matchFunding: "Project-specific partnership funding",
    eligibilityNotes: ["Grassroots football clubs, charities and local authorities can be eligible", "Early project discussion is strongly advised"],
    evidenceRequirementIds: ["sustained-demand", "facility-use", "reliability-resilience", "participation-opportunity", "inclusion-reach", "monitoring-baseline"],
    manualRequirements: ["Feasibility", "Tenure", "Planning", "Business plan", "Community consultation", "Quotations", "Usage and sustainability plans"],
    officialUrl: "https://faw.cymru/cff/facilities-programme/",
  }),
  programme({
    id: "cff-stadia-improvement",
    funder: "Cymru Football Foundation",
    name: "Stadia Improvement Fund",
    nations: ["wales"],
    status: "closed",
    amountLabel: "Up to £50,000",
    projectTypes: ["floodlights", "clubhouse", "parking-access", "equipment"],
    summary: "Infrastructure improvements linked to licensing requirements, including stands, floodlights, fencing and hard-standing areas.",
    matchFunding: "Check current programme guidance",
    eligibilityNotes: ["Relevant licensing criteria and competition level apply", "Infrastructure must support the club's compliance route"],
    evidenceRequirementIds: ["organisation-identity", "sustained-demand", "site-access", "monitoring-baseline"],
    manualRequirements: ["Licensing gap evidence", "Project drawings", "Quotations", "Planning or landlord consent", "Budget"],
    officialUrl: "https://faw.cymru/cff/stadia-improvement-fund/",
  }),
  programme({
    id: "cff-sustainability-fund",
    funder: "Cymru Football Foundation",
    name: "Sustainability Fund",
    nations: ["wales"],
    status: "closed",
    amountLabel: "Up to £20,000",
    projectTypes: ["sustainability", "floodlights", "clubhouse"],
    summary: "Solar, biodiversity, sustainable lighting, water efficiency and other environmental improvements.",
    matchFunding: "Check current programme guidance",
    eligibilityNotes: ["Project must deliver a defined sustainability benefit", "Football facility use must be clear"],
    evidenceRequirementIds: ["facility-use", "reliability-resilience", "monitoring-baseline"],
    manualRequirements: ["Energy or water baseline", "Supplier quotations", "Projected savings", "Project plan", "Permissions"],
    officialUrl: "https://faw.cymru/cff/sustainability-fund/",
  }),
  programme({
    id: "sport-wales-place-for-sport",
    funder: "Sport Wales",
    name: "A Place for Sport Crowdfunder",
    nations: ["wales"],
    status: "rolling",
    amountLabel: "Up to £15,000",
    projectTypes: ["clubhouse", "equipment", "parking-access", "sustainability", "grass-pitch", "artificial-pitch"],
    summary: "Crowdfunding support for facility improvements by not-for-profit sports clubs and community groups in Wales.",
    matchFunding: "Crowdfunding route",
    eligibilityNotes: ["Not-for-profit sports club or community group", "Facility improvement project in Wales"],
    evidenceRequirementIds: ["sustained-demand", "facility-use", "participation-opportunity", "monitoring-baseline"],
    manualRequirements: ["Crowdfunding plan", "Project budget", "Community support", "Quotations", "Organisation documents"],
    officialUrl: "https://sport.wales/funding/crowdfunder",
  }),
  programme({
    id: "sport-wales-be-active",
    funder: "Sport Wales",
    name: "Be Active Wales Fund",
    nations: ["wales"],
    status: "open",
    openDate: "2026-07-08",
    deadline: "2026-09-11",
    fullApplicationDeadline: "2026-09-16",
    amountLabel: "Up to £50,000",
    decisionTime: "Check the current application timetable",
    projectTypes: ["equipment", "workforce", "participation", "women-girls", "disability-inclusion"],
    summary: "National Lottery support for equipment and coaching courses for not-for-profit sports clubs and community groups in Wales.",
    matchFunding: "At least 10%; awards above £25,000 normally fund up to 80%",
    eligibilityNotes: ["Not-for-profit sports club or community group", "Project must increase or sustain participation", "The 2026 application window is open; EOI deadline 11 September 2026"],
    evidenceRequirementIds: ["participation-opportunity", "inclusion-reach", "workforce", "monitoring-baseline"],
    manualRequirements: ["Participation plan", "Equipment or course quotations", "Beneficiary information", "Governance documents", "Outcome plan"],
    officialUrl: "https://sport.wales/funding/be-active-wales",
  }),
  programme({
    id: "sport-wales-energy-saving",
    funder: "Sport Wales",
    name: "Energy Saving Grant",
    nations: ["wales"],
    status: "closed",
    deadline: "2026-07-01",
    nextReviewOn: "2026-10-08",
    amountLabel: "Up to £25,000",
    projectTypes: ["sustainability", "clubhouse", "floodlights"],
    summary: "Energy-saving improvements for not-for-profit sports clubs and community groups in Wales.",
    matchFunding: "Club contribution of at least 20%",
    eligibilityNotes: ["Energy-saving project in Wales", "Not-for-profit sports club or community group", "The 2026 EOI and stage-one windows are closed; stage two is invitation-only"],
    evidenceRequirementIds: ["facility-use", "monitoring-baseline"],
    manualRequirements: ["Energy baseline", "Projected savings", "Quotations", "Permissions", "Organisation documents"],
    officialUrl: "https://sport.wales/funding/energy-saving-grant",
  }),
  programme({
    id: "tnl-awards-all-wales",
    funder: "The National Lottery Community Fund",
    name: "Awards for All Wales",
    nations: ["wales"],
    status: "open",
    amountLabel: "£300 to £20,000",
    projectTypes: ["participation", "community", "women-girls", "disability-inclusion", "equipment", "clubhouse", "workforce"],
    summary: "Community-led projects that bring people together and improve communities in Wales.",
    matchFunding: "No standard match-funding requirement stated on the programme overview",
    eligibilityNotes: ["Projects can last up to two years", "Decision target is around 12 weeks"],
    evidenceRequirementIds: ["participation-opportunity", "inclusion-reach", "sustained-demand", "monitoring-baseline"],
    manualRequirements: ["Community need", "Project plan", "Budget", "Organisation documents", "Outcomes"],
    officialUrl: "https://www.tnlcommunityfund.org.uk/funding/funding-programmes/national-lottery-awards-for-all-wales",
  }),
  programme({
    id: "tnl-people-places-wales",
    funder: "The National Lottery Community Fund",
    name: "People and Places",
    nations: ["wales"],
    status: "open",
    amountLabel: "£20,001 to £500,000",
    projectTypes: ["community", "participation", "clubhouse", "asset-transfer", "disability-inclusion", "women-girls"],
    summary: "Larger community-led projects in Wales focused on issues local people identify as important.",
    matchFunding: "Check current programme guidance",
    eligibilityNotes: ["Accessible and community-led project", "Decision target is around 40 weeks"],
    evidenceRequirementIds: ["sustained-demand", "participation-opportunity", "inclusion-reach", "monitoring-baseline"],
    manualRequirements: ["Detailed community consultation", "Business and delivery plan", "Budget", "Governance", "Outcome and evaluation plan"],
    officialUrl: "https://www.tnlcommunityfund.org.uk/funding/funding-programmes/people-and-places",
  }),
  programme({
    id: "sportscotland-facilities-fund",
    funder: "sportscotland",
    name: "Sport Facilities Fund",
    nations: ["scotland"],
    status: "open",
    deadline: "2026-09-01",
    amountLabel: "Project-specific capital awards",
    projectTypes: ["grass-pitch", "artificial-pitch", "clubhouse", "floodlights", "parking-access", "disability-inclusion"],
    summary: "Capital investment to create or improve places for sport, with priority for projects delivering strong inclusion and equality outcomes.",
    matchFunding: "Project-specific partnership funding",
    eligibilityNotes: ["Discuss the project before applying", "Annual deadlines are 1 April and 1 September", "Inclusive impact is a core priority"],
    evidenceRequirementIds: ["sustained-demand", "facility-use", "inclusion-reach", "participation-opportunity", "monitoring-baseline"],
    manualRequirements: ["Pre-application discussion", "Feasibility", "Tenure", "Planning", "Budget and match funding", "Equality and inclusion case", "Business plan"],
    officialUrl: "https://sportscotland.org.uk/funding/sport-facilities-fund",
  }),
  programme({
    id: "tnl-awards-all-scotland",
    funder: "The National Lottery Community Fund",
    name: "Awards for All Scotland",
    nations: ["scotland"],
    status: "open",
    amountLabel: "£300 to £20,000",
    projectTypes: ["participation", "community", "women-girls", "disability-inclusion", "equipment", "clubhouse", "workforce"],
    summary: "Community projects in Scotland that bring people together and improve communities.",
    matchFunding: "No standard match-funding requirement stated on the programme overview",
    eligibilityNotes: ["Projects can last up to two years", "Decision target is around 12 weeks"],
    evidenceRequirementIds: ["participation-opportunity", "inclusion-reach", "sustained-demand", "monitoring-baseline"],
    manualRequirements: ["Community need", "Project plan", "Budget", "Organisation documents", "Outcomes"],
    officialUrl: "https://www.tnlcommunityfund.org.uk/funding/funding-programmes/national-lottery-awards-for-all-scotland",
  }),
  programme({
    id: "tnl-fairer-life-chances",
    funder: "The National Lottery Community Fund",
    name: "Fairer Life Chances",
    nations: ["scotland"],
    status: "open",
    amountLabel: "£20,001 to £500,000",
    projectTypes: ["community", "participation", "women-girls", "disability-inclusion", "workforce"],
    summary: "Larger Scottish projects supporting children, young people and families or helping people become healthier with better access to support.",
    matchFunding: "Check current programme guidance",
    eligibilityNotes: ["Project must fit the stated mission and target groups", "Decision target is around 12 weeks"],
    evidenceRequirementIds: ["participation-opportunity", "inclusion-reach", "sustained-demand", "monitoring-baseline"],
    manualRequirements: ["Needs analysis", "Partnerships", "Detailed delivery plan", "Budget", "Safeguarding", "Outcome and evaluation framework"],
    officialUrl: "https://www.tnlcommunityfund.org.uk/funding/funding-programmes/fairer-life-chances",
  }),
  programme({
    id: "scottish-land-fund",
    funder: "The National Lottery Community Fund",
    name: "Scottish Land Fund",
    nations: ["scotland"],
    status: "open",
    amountLabel: "£5,000 to £1,000,000",
    projectTypes: ["asset-transfer", "clubhouse", "grass-pitch", "artificial-pitch"],
    summary: "Support for communities in Scotland to own and manage land and buildings sustainably.",
    matchFunding: "Project-specific contribution requirements",
    eligibilityNotes: ["Community ownership route", "Strong community support and sustainable use are required", "Decision target is around 16 weeks"],
    evidenceRequirementIds: ["organisation-identity", "sustained-demand", "facility-use", "participation-opportunity", "monitoring-baseline"],
    manualRequirements: ["Community body eligibility", "Valuation", "Business plan", "Community consultation", "Purchase or transfer terms", "Finance plan"],
    officialUrl: "https://www.tnlcommunityfund.org.uk/funding/funding-programmes/scottish-land-fund",
  }),
  programme({
    id: "irish-fa-dcms-2026-27",
    funder: "Irish FA / Department for Culture, Media and Sport",
    name: "Grassroots Facilities Investment Fund 2026–27",
    nations: ["northern-ireland"],
    status: "closed",
    deadline: "2026-03-18",
    amountLabel: "£100,000 to £500,000",
    projectTypes: ["grass-pitch", "artificial-pitch", "clubhouse", "floodlights", "parking-access"],
    summary: "Large capital projects centred on natural grass pitches, certified artificial grass pitches or multi-use games areas in Northern Ireland.",
    matchFunding: "Partner match funding required",
    eligibilityNotes: ["2026–27 deadline has passed", "Pitch proposal must be central", "Affiliation or eligible public/community body status required", "Completion was required by 31 March 2027"],
    evidenceRequirementIds: ["sustained-demand", "facility-use", "participation-opportunity", "inclusion-reach", "monitoring-baseline"],
    manualRequirements: ["Eligibility evidence", "Usage plan", "Match funding", "Planning", "Tenure", "Detailed project cost", "Participation and inclusion outcomes"],
    officialUrl: "https://www.irishfa.com/irish-football-association/irish-fa-dcms-grassroots-facilities-investment-fund",
  }),
  programme({
    id: "ni-grassroots-facilities-pilot",
    funder: "Department for Communities / Irish FA",
    name: "Northern Ireland Grassroots Facilities Programme Pilot",
    nations: ["northern-ireland"],
    status: "monitor",
    amountLabel: "Indicative awards of £500,000 to £1.5 million",
    projectTypes: ["grass-pitch", "artificial-pitch", "clubhouse", "floodlights", "parking-access"],
    summary: "Announced pilot for major grassroots football facility investment in Northern Ireland, with detailed application arrangements to be monitored.",
    matchFunding: "To be confirmed in programme guidance",
    eligibilityNotes: ["Programme details and application route must be verified before any application work", "Large capital facility focus"],
    evidenceRequirementIds: ["sustained-demand", "facility-use", "participation-opportunity", "inclusion-reach", "monitoring-baseline"],
    manualRequirements: ["Full guidance when published", "Feasibility", "Tenure", "Planning", "Business plan", "Capital funding package", "Outcomes framework"],
    officialUrl: "https://www.irishfa.com/news/2026/march/kirkwood-welcomes-funding-for-grassroots-facilities",
  }),
  programme({
    id: "tnl-awards-all-ni",
    funder: "The National Lottery Community Fund",
    name: "Awards for All Northern Ireland",
    nations: ["northern-ireland"],
    status: "open",
    amountLabel: "£300 to £20,000",
    projectTypes: ["participation", "community", "women-girls", "disability-inclusion", "equipment", "clubhouse", "workforce"],
    summary: "Projects that connect people and strengthen communities in Northern Ireland.",
    matchFunding: "No standard match-funding requirement stated on the programme overview",
    eligibilityNotes: ["Projects can last up to two years", "Decision target is around 12 weeks"],
    evidenceRequirementIds: ["participation-opportunity", "inclusion-reach", "sustained-demand", "monitoring-baseline"],
    manualRequirements: ["Community need", "Project plan", "Budget", "Organisation documents", "Outcomes"],
    officialUrl: "https://www.tnlcommunityfund.org.uk/funding/funding-programmes/national-lottery-awards-for-all-northern-ireland",
  }),
  programme({
    id: "tnl-dormant-assets-ni",
    funder: "The National Lottery Community Fund",
    name: "Dormant Assets for All",
    nations: ["northern-ireland"],
    status: "open",
    amountLabel: "£300 to £20,000",
    projectTypes: ["workforce", "community", "participation"],
    summary: "Capacity-building support for voluntary, community and social enterprise organisations in Northern Ireland.",
    matchFunding: "Check current programme guidance",
    eligibilityNotes: ["Organisation-strengthening focus", "Not a general capital sports facility fund"],
    evidenceRequirementIds: ["organisation-identity", "workforce", "monitoring-baseline"],
    manualRequirements: ["Organisational development need", "Capacity plan", "Governance", "Budget", "Sustainability outcomes"],
    officialUrl: "https://www.tnlcommunityfund.org.uk/funding/funding-programmes/dormant-assets-for-all",
  }),
];

export function getProjectTypeDefinition(value = "all") {
  return GRANT_PROJECT_TYPES.find((item) => item.value === value) || GRANT_PROJECT_TYPES[0];
}

export default VERIFIED_GRANT_PROGRAMMES;
