import { ArrowRight, Building2, CalendarRange, Check, ChevronRight, CircleDollarSign, RadioTower, ShieldCheck, Sparkles, Trophy, UsersRound } from "lucide-react";

const products = [
  { name: "Ground Control", label: "Live", Icon: RadioTower, tone: "from-emerald-400/25 to-cyan-400/5", copy: "The operational command centre for fixtures, facilities, officials, communications and club readiness." },
  { name: "Coach Hub", label: "Connected", Icon: UsersRound, tone: "from-sky-400/25 to-blue-400/5", copy: "A focused team workspace for coach requests, calendars, conversations and matchday information." },
  { name: "League Manager", label: "Pilot", Icon: Trophy, tone: "from-violet-400/25 to-purple-400/5", copy: "Competition-wide control for fixtures, clubs, cups, officials, discipline and league operations." },
  { name: "Daxora Pay", label: "In development", Icon: CircleDollarSign, tone: "from-amber-400/25 to-orange-400/5", copy: "One future financial workspace for memberships, collections, arrears, reconciliation and reporting." },
];

export default function DaxoraLandingPage({ onSignIn, onCreateAccount }) {
  return <div className="min-h-screen overflow-hidden bg-[#050816] text-white">
    <header className="relative z-20 border-b border-white/10 bg-[#050816]/80 backdrop-blur-xl"><div className="mx-auto flex h-20 max-w-7xl items-center justify-between px-5 sm:px-8"><a href="#top" className="text-xl font-black uppercase tracking-[0.2em]">Daxora<span className="text-emerald-400">.</span></a><nav className="hidden items-center gap-7 text-xs font-black text-slate-400 md:flex"><a href="#products" className="hover:text-white">Products</a><a href="#platform" className="hover:text-white">Platform</a><a href="#why" className="hover:text-white">Why Daxora</a></nav><button type="button" onClick={onSignIn} className="inline-flex h-11 items-center gap-2 rounded-xl border border-white/15 bg-white px-4 text-xs font-black text-slate-950 hover:bg-emerald-300">Sign in <ArrowRight size={15} /></button></div></header>

    <main id="top">
      <section className="relative"><div className="absolute inset-0 bg-[radial-gradient(circle_at_75%_15%,rgba(45,212,191,.16),transparent_32%),radial-gradient(circle_at_20%_75%,rgba(37,99,235,.14),transparent_36%)]" /><div className="relative mx-auto grid min-h-[720px] max-w-7xl items-center gap-14 px-5 py-20 sm:px-8 lg:grid-cols-[1.15fr_.85fr] lg:py-28"><div><div className="inline-flex items-center gap-2 rounded-full border border-emerald-400/25 bg-emerald-400/10 px-4 py-2 text-[10px] font-black uppercase tracking-[0.2em] text-emerald-300"><Sparkles size={14} /> The connected operating platform for grassroots sport</div><h1 className="mt-8 max-w-4xl text-5xl font-black leading-[.98] tracking-[-.05em] sm:text-7xl">Run the whole organisation.<br /><span className="bg-gradient-to-r from-emerald-300 to-cyan-400 bg-clip-text text-transparent">Without the chaos.</span></h1><p className="mt-7 max-w-2xl text-lg font-semibold leading-8 text-slate-300">Daxora brings club operations, coaching, competitions and payments into one secure platform—with one identity and one reliable source of truth.</p><div className="mt-9 flex flex-wrap gap-3"><button type="button" onClick={onSignIn} className="inline-flex h-13 items-center gap-2 rounded-2xl bg-emerald-400 px-6 text-sm font-black text-slate-950 shadow-[0_0_40px_rgba(52,211,153,.2)] hover:bg-emerald-300">Open Daxora <ArrowRight size={17} /></button><a href="#products" className="inline-flex h-13 items-center gap-2 rounded-2xl border border-white/15 bg-white/[0.04] px-6 text-sm font-black text-white hover:bg-white/[0.08]">Explore products <ChevronRight size={17} /></a></div><div className="mt-10 flex flex-wrap gap-x-6 gap-y-3 text-xs font-bold text-slate-400">{["Role-aware access", "One organisation record", "Secure cloud platform"].map((item) => <span key={item} className="inline-flex items-center gap-2"><span className="flex h-5 w-5 items-center justify-center rounded-full bg-emerald-400/15 text-emerald-300"><Check size={12} /></span>{item}</span>)}</div></div>
      <div className="relative"><div className="absolute -inset-8 rounded-full bg-emerald-400/10 blur-3xl" /><div className="relative rounded-[34px] border border-white/15 bg-white/[0.06] p-4 shadow-2xl backdrop-blur-xl"><div className="rounded-[27px] border border-white/10 bg-[#0b1222] p-6"><div className="flex items-center justify-between"><div><div className="text-[9px] font-black uppercase tracking-[0.22em] text-emerald-300">Daxora Platform</div><div className="mt-2 text-xl font-black">One secure account</div></div><ShieldCheck className="text-emerald-300" size={28} /></div><div className="mt-7 space-y-3">{products.map(({ name, Icon }, index) => <div key={name} className={`flex items-center gap-3 rounded-2xl border px-4 py-3 ${index === 0 ? "border-emerald-400/25 bg-emerald-400/10" : "border-white/10 bg-white/[0.03]"}`}><span className="flex h-10 w-10 items-center justify-center rounded-xl bg-white/10"><Icon size={19} /></span><span className="flex-1 text-sm font-black">{name}</span><span className="text-[9px] font-black uppercase tracking-wide text-slate-500">{index === 0 ? "Open" : index === 3 ? "Soon" : "Connected"}</span></div>)}</div><div className="mt-6 rounded-2xl border border-white/10 bg-white/[0.03] p-4"><div className="flex items-center gap-3"><Building2 size={18} className="text-sky-300" /><div><div className="text-xs font-black">Organisation-aware</div><div className="mt-1 text-[10px] font-semibold text-slate-500">Products follow the club, league and roles you select.</div></div></div></div></div></div></div></div></section>

      <section id="products" className="border-y border-white/10 bg-white/[0.025] py-24"><div className="mx-auto max-w-7xl px-5 sm:px-8"><div className="max-w-3xl"><div className="text-[10px] font-black uppercase tracking-[0.24em] text-emerald-300">The Daxora product family</div><h2 className="mt-4 text-4xl font-black tracking-tight sm:text-5xl">Specialist products. One connected platform.</h2><p className="mt-5 text-base font-semibold leading-7 text-slate-400">Use what your organisation needs today. Add capabilities without adding new accounts, isolated data or duplicated administration.</p></div><div className="mt-12 grid gap-4 md:grid-cols-2">{products.map(({ name, label, Icon, tone, copy }) => <article key={name} className={`rounded-[28px] border border-white/10 bg-gradient-to-br ${tone} p-7`}><div className="flex items-start justify-between gap-3"><span className="flex h-12 w-12 items-center justify-center rounded-2xl bg-white/10"><Icon size={23} /></span><span className="rounded-full border border-white/10 bg-black/15 px-3 py-1 text-[9px] font-black uppercase tracking-wide text-slate-300">{label}</span></div><h3 className="mt-8 text-2xl font-black">{name}</h3><p className="mt-3 max-w-xl text-sm font-semibold leading-6 text-slate-300">{copy}</p></article>)}</div></div></section>

      <section id="platform" className="py-24"><div className="mx-auto grid max-w-7xl gap-12 px-5 sm:px-8 lg:grid-cols-2 lg:items-center"><div><div className="text-[10px] font-black uppercase tracking-[0.24em] text-sky-300">Designed as a platform</div><h2 className="mt-4 text-4xl font-black tracking-tight sm:text-5xl">One version of the truth, everywhere.</h2><p className="mt-5 text-base font-semibold leading-7 text-slate-400">Daxora products share trusted identity, organisation, role and subscription context. People see the work they are responsible for—without gaining access to anything else.</p></div><div id="why" className="grid gap-4 sm:grid-cols-2">{[[CalendarRange,"Less repeated work","Fixtures and operational context move through connected workflows."],[UsersRound,"Roles that make sense","Multi-role users receive the combined access their responsibilities require."],[ShieldCheck,"Security by design","Every product enforces permissions at the interface, service and data layers."],[Building2,"Built for real organisations","Clubs, teams, sites and leagues remain clearly separated and connected."]].map(([Icon,title,copy]) => <div key={title} className="rounded-3xl border border-white/10 bg-white/[0.04] p-6"><Icon size={22} className="text-emerald-300" /><h3 className="mt-5 text-lg font-black">{title}</h3><p className="mt-2 text-sm font-semibold leading-6 text-slate-400">{copy}</p></div>)}</div></div></section>

      <section className="px-5 pb-24 sm:px-8"><div className="mx-auto max-w-7xl overflow-hidden rounded-[34px] bg-gradient-to-r from-emerald-400 to-cyan-400 p-8 text-slate-950 sm:p-12"><div className="flex flex-col justify-between gap-8 lg:flex-row lg:items-center"><div><h2 className="text-3xl font-black tracking-tight sm:text-4xl">Already part of Daxora?</h2><p className="mt-3 max-w-2xl text-sm font-bold text-slate-800/75">Sign in once, choose your organisation and open the product you need.</p></div><div className="flex flex-wrap gap-3"><button type="button" onClick={onSignIn} className="h-12 rounded-2xl bg-slate-950 px-6 text-sm font-black text-white">Sign in</button><button type="button" onClick={onCreateAccount} className="h-12 rounded-2xl border border-slate-950/20 bg-white/40 px-6 text-sm font-black">Create account</button></div></div></div></section>
    </main>
    <footer className="border-t border-white/10 px-5 py-8 sm:px-8"><div className="mx-auto flex max-w-7xl flex-col gap-3 text-xs font-bold text-slate-500 sm:flex-row sm:items-center sm:justify-between"><span className="uppercase tracking-[0.2em] text-slate-300">Daxora</span><span>Connected operations for grassroots sport.</span><span>© 2026 Daxora</span></div></footer>
  </div>;
}
