import { CalendarRange, CloudRain, PoundSterling, RefreshCw, Snowflake, UsersRound } from "lucide-react";

function money(pence) {
  return new Intl.NumberFormat("en-GB", { style: "currency", currency: "GBP" }).format((Number(pence) || 0) / 100);
}

function Metric({ icon: Icon, label, value, detail, tone = "slate" }) {
  const tones = {
    slate: "bg-slate-100 text-slate-700",
    sky: "bg-sky-100 text-sky-700",
    amber: "bg-amber-100 text-amber-700",
    violet: "bg-violet-100 text-violet-700",
    emerald: "bg-emerald-100 text-emerald-700",
    rose: "bg-rose-100 text-rose-700",
  };
  return <div className="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm"><div className="flex items-start justify-between gap-3"><div><div className="text-[10px] font-black uppercase tracking-[0.14em] text-slate-500">{label}</div><div className="mt-2 text-2xl font-black text-slate-950">{value}</div><div className="mt-1 text-xs font-semibold leading-5 text-slate-500">{detail}</div></div><span className={`flex h-10 w-10 shrink-0 items-center justify-center rounded-xl ${tones[tone] || tones.slate}`}><Icon size={18} /></span></div></div>;
}

export default function AnnualPlannerAnalyticsSummary({ model, title = "Training and facility evidence", subtitle = "One shared analytics layer across Annual Planner Insights, club analytics and grant evidence.", compact = false, onRefresh, refreshing = false }) {
  const metrics = model?.metrics || {};
  if (!model?.hasData) return <section className="rounded-[28px] border border-dashed border-slate-300 bg-slate-50 p-6"><div className="flex items-start gap-3"><span className="flex h-11 w-11 items-center justify-center rounded-2xl bg-white text-slate-500 shadow-sm"><CalendarRange size={20} /></span><div><h3 className="text-lg font-black text-slate-900">Annual Planner analytics are ready</h3><p className="mt-1 text-sm font-semibold leading-6 text-slate-500">Add training bookings, winter sites or weather outcomes to build shared operational and grant evidence.</p></div></div></section>;
  return <section className="rounded-[28px] border border-slate-200 bg-slate-50/70 p-5 shadow-sm sm:p-6"><div className="flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between"><div><div className="text-[10px] font-black uppercase tracking-[0.18em] text-emerald-700">Annual Planner intelligence</div><h2 className="mt-1 text-xl font-black text-slate-950">{title}</h2><p className="mt-2 max-w-3xl text-sm font-semibold leading-6 text-slate-500">{subtitle}</p></div>{onRefresh ? <button type="button" onClick={onRefresh} disabled={refreshing} className="inline-flex h-10 items-center justify-center gap-2 rounded-xl border border-slate-200 bg-white px-4 text-xs font-black text-slate-700 disabled:opacity-50"><RefreshCw size={15} className={refreshing ? "animate-spin" : ""} /> Refresh evidence</button> : null}</div><div className={`mt-5 grid gap-3 ${compact ? "sm:grid-cols-2 xl:grid-cols-4" : "sm:grid-cols-2 xl:grid-cols-4"}`}><Metric icon={CalendarRange} label="Planned hours" value={metrics.plannedHours || 0} detail="Active annual bookings" tone="sky" /><Metric icon={CloudRain} label="Weather lost" value={`${metrics.weatherLostHours || 0}h`} detail={`${metrics.weatherAffectedSessions || 0} affected sessions`} tone={metrics.weatherLostHours ? "rose" : "emerald"} /><Metric icon={Snowflake} label="Winter provision" value={`${metrics.winterHours || 0}h`} detail={`${metrics.activeWinterSites || 0} active sites · ${metrics.fixedWinterSlots || 0} fixed slots`} tone="violet" /><Metric icon={PoundSterling} label="Winter cost" value={money(metrics.externalWinterCostPence)} detail="Recorded external provision" tone="amber" /></div>{!compact ? <div className="mt-5 grid gap-4 xl:grid-cols-[minmax(0,1fr)_360px]"><div className="overflow-hidden rounded-2xl border border-slate-200 bg-white"><div className="grid grid-cols-[minmax(150px,1fr)_80px_90px_100px] gap-3 bg-slate-50 px-4 py-3 text-[10px] font-black uppercase tracking-wide text-slate-500"><span>Facility</span><span>Bookings</span><span>Hours</span><span>Weather loss</span></div>{model.pitchRows?.slice(0, 8).map((row) => <div key={row.id} className="grid grid-cols-[minmax(150px,1fr)_80px_90px_100px] gap-3 border-t border-slate-100 px-4 py-3 text-xs"><span className="font-black text-slate-900">{row.label}</span><span className="font-bold text-slate-600">{row.bookings}</span><span className="font-bold text-slate-600">{row.hours}</span><span className="font-black text-rose-700">{row.weatherLostHours}h</span></div>)}</div><div className="rounded-2xl border border-emerald-200 bg-emerald-50 p-4"><div className="flex items-center gap-2 text-xs font-black uppercase tracking-[0.14em] text-emerald-800"><UsersRound size={16} /> Grant evidence narrative</div><ul className="mt-3 space-y-2 text-xs font-semibold leading-5 text-emerald-950">{model.grantNarratives?.map((row) => <li key={row}>• {row}</li>)}</ul></div></div> : null}</section>;
}
